//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRentalRecord
    {
        public int carRentalRecord_id { get; set; }
        public string customerFirstName { get; set; }
        public string customerLastName { get; set; }
        public Nullable<System.DateTime> dateRented { get; set; }
        public Nullable<System.DateTime> dateReturned { get; set; }
        public Nullable<decimal> cost { get; set; }
        public int IdCarType { get; set; }
    
        public virtual carType carType { get; set; }
    }
}
